const PAYMENT_PREFIX = '/payment/v1/public'
const ETC_API_PREFIX = '/etc/v1/public'
const MEMBER_AUTH_API_PREFIX = '/member/v1'
const OTP_AUTH_PREFIX = '/member/v1/public/otp/register'
const USER_PREFIX = 'v1/public/users'
const PAYMENT_PREFIX_NEW = 'member/v1/public/payment'
export const MEMBER_API_PREFIX = '/member/v1/public'
export const SNS_LOGIN_ENDPOINT = `${MEMBER_API_PREFIX}/login`
export const CHECK_EXIST_ACCOUNT_ENDPOINT = `${MEMBER_API_PREFIX}/users/findExistUser`
export const REGISTER_ENDPOINT = `${MEMBER_API_PREFIX}/users/register`
export const REGISTER_INIT_ENDPOINT = `${MEMBER_API_PREFIX}/users/register/init`
export const USERNAME_LOGIN_ENDPOINT = `/oauth/token`
export const GEN_URL_CREDIT_CARD = `${PAYMENT_PREFIX_NEW}/world-pay/credit-card/register/generate-url`
export const GET_STATUS_PAYMENT = `${PAYMENT_PREFIX_NEW}/payment/status`
export const GET_TERMS_ENDPOINT = `${ETC_API_PREFIX}/terms/signUp`
export const CREDIT_CARD_REGISTER = `${PAYMENT_PREFIX}/credit-card/register`
export const SEND_AUTH_MAIL_ENDPOINT = `${OTP_AUTH_PREFIX}/email/send`
export const SEND_CODE_MAIL_ENDPOINT = `${OTP_AUTH_PREFIX}/email/verify`
export const SEND_PHONE_ENDPOINT = `${USER_PREFIX}/sendCertificationNumber`
export const VERIFY_CODE_PHONE_ENDPOINT = `${USER_PREFIX}/validateCertificationNumber`
export const SEND_PHONE_CARD_ENDPOINT = `${MEMBER_API_PREFIX}/otp/phone/send`
export const VERIFY_CODE_PHONE_CARD_ENDPOINT = `${MEMBER_API_PREFIX}/otp/register/phone/verify`
export const VERIFY_SSN_ENDPOINT = `${MEMBER_API_PREFIX}/identity/verify`
export const BUSINESS_INFORMATION_ENDPOINT = `${MEMBER_AUTH_API_PREFIX}/users/company`
export const SEARCH_ADDRESS_ENDPOINT = `${MEMBER_API_PREFIX}/loqate/address/search`
export const VERIFY_ADDRESS_ENDPOINT = `${MEMBER_API_PREFIX}/loqate/address/verify`
export const VALIDATE_MOBILE_PHONE = `${MEMBER_API_PREFIX}/loqate/mobileVerify`
export const FIND_ACCOUNT_SEND = `${MEMBER_API_PREFIX}/users/findAccount/send`
export const FIND_ACCOUNT_VERIFY = `${MEMBER_API_PREFIX}/users/findAccount/verify`
export const FIND_USER_PASSWORD_ENDPOINT = `${MEMBER_API_PREFIX}/users/findUserPassword`
export const CHANGE_USER_PASSWORD_ENDPOINT = `${MEMBER_API_PREFIX}/users/passwordResetFromEmail`
export const GET_CURRENT_USER_ENDPOINT = `/member/v1/users/me`
export const SEARCH_RECOMMENDER_CODE = `${MEMBER_API_PREFIX}/recommender/referral-code`
export const SEARCH_RECOMMENDER_NAME = `${MEMBER_API_PREFIX}/recommender/referral-number`
export const SEARCH_RECOMMENDER_GLOBAL = `${MEMBER_API_PREFIX}/recommender/referral-global`
export const TERMS_FOOTER_POLICY = `${ETC_API_PREFIX}/terms/find`
export const MEMBERSHIP_FEE_ENDPOINT = `${MEMBER_API_PREFIX}/users/beautyPlanner/membership-fee`
export const AUTH_EMAIL_ENDPOINT = `${MEMBER_API_PREFIX}/loqate/emailVerify`
export const AUTH_ADDRESS_ENDPOINT = `${MEMBER_API_PREFIX}/loqate/addressVerify`
export const SAVE_QR_CODE_ENDPOINT = `${MEMBER_API_PREFIX}/login/save-code`
export const LOGIN_WITH_QR_CODE_ENDPOINT = `${MEMBER_API_PREFIX}/login/scan-code`
// export const SAVE_QR_CODE_ENDPOINT = `http://10.0.65.137:7083/v1/public/login/save-code`
// export const LOGIN_WITH_QR_CODE_ENDPOINT = `http://10.0.65.137:7083/v1/public/login/scan-code`
